version: '3.9'

services:
  api: &api
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    image: messaging-dev-deploy
    command: daphne -b 0.0.0.0 -p 9542 core.asgi:application
    volumes:
      - ./app:/app
    ports:
      - '9542:9542'

    env_file:
      - ./.env
    restart: unless-stopped

  redis:
    image: bitnami/redis
    ports:
      - "6739:6739"
    env_file:
      - ./.env
